name: Clustertool-go-lint
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - "*"
  #   paths:
  #     - 'main.go'
  #     - 'go.mod'
  #     - 'go.sum'
  #     - 'pkg/**'
  #     - 'cmd/**'
  #     - 'clustertool/**'
  #     - ".github/workflows/clsutertool.test.yaml"
  pull_request:
    branches:
      - main
    paths:
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'pkg/**'
      - 'cmd/**'
      - 'clustertool/**'
      - ".github/workflows/clustertool.test.yaml"
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: actions-runners
    steps:
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version: stable
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: latest
          args: --timeout 3m0s
