name: Clustertool-go-lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
    paths:
      - 'clustertool/**'
      - '.github/workflows/clustertool.lint.yaml'

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
        with:
          go-version: stable
          cache: false   # bewust uit, voorkomt go.sum-pad issues

      - name: Run golangci-lint (minimal)
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9
        with:
          version: latest
          working-directory: clustertool
          args: >
            --timeout=3m
            --enable-only=ineffassign,unused