name: Clustertool-go-lint

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - main
    paths:
      - 'clustertool/**'
      - '.github/workflows/clustertool.lint.yaml'

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: stable
          cache: false   # bewust uit, voorkomt go.sum-pad issues

      - name: Run golangci-lint (minimal)
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9
        with:
          version: latest
          working-directory: clustertool
          args: >
            --timeout=3m
            --enable-only=ineffassign,unused