name: clustertool-go-release
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    tags:
      - "*"
    paths:
      - 'clustertool/**'
jobs:
  goreleaser:
    # runs-on: actions-runners  ## Changed by Boemeltrein
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6
        with:
          go-version: stable
          cache: true
          cache-dependency-path: |
            **/go.mod
            **/go.sum
      # - name: Install Syft
      #   run: sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          args: release --clean --config clustertool/.goreleaser.yaml   ## ADDED --config by Boemeltrein
          distribution: goreleaser # or 'goreleaser-pro'
          version: "~> v2" # or 'latest', 'nightly', semver
        env:
          # GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"   ## CHANGED FROM UPSTREAM
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
